name: Playwright Tests
on:
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXT_PUBLIC_S3_RESIZED_IMAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_S3_RESIZED_IMAGE_BUCKET }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build app
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_S3_RESIZED_IMAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_S3_RESIZED_IMAGE_BUCKET }}
      - name: Start app
        run: npm run start &
        working-directory: packages/app
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_S3_RESIZED_IMAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_S3_RESIZED_IMAGE_BUCKET }}
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: packages/app
        env:
          TEST_BASE_URL: http://localhost:3000
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_S3_RESIZED_IMAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_S3_RESIZED_IMAGE_BUCKET }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: packages/app/playwright-report/
          retention-days: 30
